version: '3.8'

services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: gin-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gin
      MYSQL_USER: gin_user
      MYSQL_PASSWORD: gin_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - gin-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s

  # Go 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gin-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # 数据库配置
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: gin_user
      DB_PASSWORD: gin_password
      DB_NAME: gin
      # 应用配置
      GIN_MODE: release
      PORT: 8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gin-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      timeout: 10s
      retries: 3
      start_period: 40s
      interval: 30s

# 网络配置
networks:
  gin-network:
    driver: bridge

# 数据卷配置
volumes:
  mysql_data:
    driver: local 